name: Make DB Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -X GET ${{ secrets.MAKE_DB_ALIVE }}

