name: Ping Render API

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -X GET ${{ secrets.RENDER_API }}

